<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKtC7elU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKtC7elU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKtC7elU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKtC7elU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKtC7elU\App_KernelDevDebugContainer([
    'container.build_hash' => 'KtC7elU',
    'container.build_id' => '59729757',
    'container.build_time' => 1576265671,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKtC7elU');
