<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQsRVktY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQsRVktY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQsRVktY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQsRVktY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQsRVktY\App_KernelDevDebugContainer([
    'container.build_hash' => 'QsRVktY',
    'container.build_id' => '081e257b',
    'container.build_time' => 1576579667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQsRVktY');
